// Code generated by "stringer -type itemType"; DO NOT EDIT

package boolean

import "fmt"

const _itemType_name = "itemErroritemIdentifieritemAnditemOritemNotitemLeftParenitemRightParenitemEOF"

var _itemType_index = [...]uint8{0, 9, 23, 30, 36, 43, 56, 70, 77}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
